name: Coding Standards
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: MilesChou/composer-action@master
      with:
        args: config http-basic.repo.magento.com 7bdd660a63609d2af9fcbc033a9eae8d 77c0cedb4871620c63acbd82aeb92f38
    - uses: MilesChou/composer-action@master
      with:
        args: install --prefer-dist --ignore-platform-reqs
    - name: PHP CS
      run: ./vendor/bin/phpcs --colors --standard=Magento2 --report=full,summary,gitblame --extensions=php,phtml --ignore=./vendor/ ./      
    - name: PHP Compatibility
      run: ./vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion 7.0-7.3 --colors --warning-severity=0 --report=full,summary --extensions=php,phtml --ignore=./vendor/ ./
    - name: PHP CS Fixer
      run: ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --dry-run --stop-on-violation --using-cache=no
    - name: PHPStan
      run: ./vendor/bin/phpstan analyze ./        